name: joinup_test
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.11.8
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - amqp==5.2.0
      - asgiref==3.8.1
      - billiard==4.2.0
      - celery==5.3.6
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - django==5.0.3
      - django-environ==0.11.2
      - django-filter==24.2
      - django-rest-authtoken==2.1.4
      - djangorestframework==3.15.1
      - iniconfig==2.0.0
      - kombu==5.3.6
      - markdown==3.6
      - packaging==24.0
      - pluggy==1.4.0
      - prompt-toolkit==3.0.43
      - pytest==8.1.1
      - pytest-django==4.8.0
      - python-dateutil==2.9.0.post0
      - redis==5.0.3
      - six==1.16.0
      - sqlparse==0.4.4
      - tzdata==2024.1
      - vine==5.1.0
      - wcwidth==0.2.13
