name: joinup_test
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.11.8
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - asgiref==3.8.1
      - django==5.0.3
      - django-environ==0.11.2
      - django-filter==24.2
      - django-rest-authtoken==2.1.4
      - djangorestframework==3.15.1
      - markdown==3.6
      - sqlparse==0.4.4
